version: '3.9'
services:
    # Explorer
    explorer:
        container_name: explorer
        build: .
        image: explorer:1.0
        ports:
            - 80:5000 # Build
            - 81:5001 #Dev
        environment:
            HOST: 0.0.0.0
        volumes:
            - .:/home/app
            - /home/app/node_modules
        working_dir: /home/app
        command: npm run dev
        # command: npm run preview